// Everyday dishes from the world's major cuisines. Same format as foods.js:
// [id, name, cat, kcal/100g, protein/100g, portions[[label, grams]], aliases]
// Values are typical home or restaurant versions, rounded; recipes vary widely, so the app
// shows them as estimates and offers gram-based portions for anyone weighing their food.
export const WORLD_CATS = [
  ["african", "African"], ["indian", "Indian & South Asian"], ["chinese", "Chinese"], ["japkor", "Japanese & Korean"],
  ["seasia", "Southeast Asian"], ["mideast", "Middle Eastern & Mediterranean"], ["latin", "Mexican & Latin American"],
  ["european", "European"], ["american", "American"]
];

export const WORLD = [
  // ---- African ----
  ["jollof", "Jollof rice", "african", 160, 3.5, [["1 plate", 300], ["1 fist (1 cup)", 175]], "jollof rice nigerian ghanaian west african"],
  ["ng-fried-rice", "Nigerian fried rice", "african", 170, 4, [["1 plate", 300], ["1 fist (1 cup)", 175]], "fried rice party rice"],
  ["waakye", "Waakye (rice and beans)", "african", 150, 5, [["1 plate", 300]], "waakye ghana rice beans"],
  ["egusi", "Egusi soup", "african", 220, 10, [["1 bowl", 250], ["1 cupped hand", 120]], "egusi melon seed soup"],
  ["efo-riro", "Efo riro (spinach stew)", "african", 120, 7, [["1 bowl", 200]], "efo riro vegetable soup"],
  ["okra-soup", "Okra soup", "african", 90, 5, [["1 bowl", 250]], "okra okro soup"],
  ["pepper-soup", "Pepper soup (goat or fish)", "african", 70, 8, [["1 bowl", 350]], "pepper soup goat meat fish"],
  ["groundnut-soup", "Groundnut / peanut soup", "african", 150, 7, [["1 bowl", 300]], "groundnut soup peanut"],
  ["mafe", "Mafé (peanut stew)", "african", 170, 10, [["1 bowl", 300]], "mafe maafe peanut stew senegal"],
  ["pounded-yam", "Pounded yam", "african", 118, 1.5, [["1 wrap / ball", 200], ["1 fist", 150]], "pounded yam iyan swallow"],
  ["fufu", "Fufu (cassava)", "african", 155, 1, [["1 wrap / ball", 200], ["1 fist", 150]], "fufu foofoo swallow"],
  ["eba", "Eba (garri)", "african", 160, 0.5, [["1 wrap / ball", 200], ["1 fist", 150]], "eba garri swallow"],
  ["banku", "Banku", "african", 130, 2, [["1 ball", 200]], "banku ghana"],
  ["kenkey", "Kenkey", "african", 140, 2.5, [["1 ball", 250]], "kenkey dokon"],
  ["ugali", "Ugali / pap / nshima", "african", 115, 2.5, [["1 serving", 250], ["1 fist", 160]], "ugali pap sadza nshima maize meal"],
  ["sukuma", "Sukuma wiki (collard greens)", "african", 50, 3, [["1 cup", 150]], "sukuma wiki kale collards"],
  ["nyama-choma", "Nyama choma (grilled meat)", "african", 230, 26, [["1 palm (100 g)", 100], ["1 plate", 250]], "nyama choma grilled goat beef braai"],
  ["suya", "Suya", "african", 250, 25, [["1 stick", 60], ["1 portion", 150]], "suya kebab spicy beef"],
  ["moi-moi", "Moi moi", "african", 150, 8, [["1 wrap", 150]], "moi moi moin moin bean pudding"],
  ["akara", "Akara (bean fritters)", "african", 280, 11, [["1 piece", 30], ["5 pieces", 150]], "akara koose bean cake"],
  ["puff-puff", "Puff-puff / mandazi", "african", 360, 6, [["1 piece", 40]], "puff puff mandazi bofrot"],
  ["beans-porridge", "Beans porridge / ewa agoyin", "african", 150, 7, [["1 bowl", 300]], "beans porridge ewa agoyin"],
  ["injera", "Injera", "african", 130, 4, [["1 injera", 120]], "injera ethiopian flatbread"],
  ["doro-wat", "Doro wat (chicken stew)", "african", 160, 13, [["1 bowl", 250]], "doro wat ethiopian chicken"],
  ["shiro", "Shiro (chickpea stew)", "african", 140, 6, [["1 bowl", 250]], "shiro wat ethiopian"],
  ["tibs", "Tibs (sautéed beef)", "african", 200, 20, [["1 serving", 200]], "tibs ethiopian beef"],
  ["chapati-ea", "Chapati (East African)", "african", 300, 7, [["1 chapati", 70]], "chapati kenya"],
  ["pilau", "Pilau rice", "african", 160, 6, [["1 plate", 300], ["1 fist", 175]], "pilau pilaf kenya"],
  ["thieboudienne", "Thieboudienne (fish and rice)", "african", 150, 8, [["1 plate", 400]], "thieboudienne ceebu jen senegal"],
  ["yassa", "Chicken yassa", "african", 150, 13, [["1 serving", 300]], "yassa senegal chicken onion"],
  ["bobotie", "Bobotie", "african", 180, 12, [["1 serving", 250]], "bobotie south africa"],
  ["boerewors", "Boerewors", "african", 300, 14, [["1 piece", 100]], "boerewors sausage braai"],
  ["kelewele", "Kelewele (spiced fried plantain)", "african", 200, 1.2, [["1 serving", 150]], "kelewele plantain"],
  ["couscous", "Couscous, cooked", "african", 112, 3.8, [["1 fist (1 cup)", 160]], "couscous"],
  ["tagine", "Chicken tagine", "african", 130, 12, [["1 bowl", 300]], "tagine moroccan chicken"],
  // ---- Indian & South Asian ----
  ["tikka-masala", "Chicken tikka masala", "indian", 150, 12, [["1 bowl", 300], ["1 cupped hand", 120]], "chicken tikka masala curry"],
  ["butter-chicken", "Butter chicken", "indian", 160, 12, [["1 bowl", 300]], "butter chicken murgh makhani"],
  ["chicken-curry-in", "Chicken curry", "indian", 130, 12, [["1 bowl", 300]], "chicken curry"],
  ["korma", "Chicken korma", "indian", 180, 12, [["1 bowl", 300]], "korma"],
  ["rogan-josh", "Lamb rogan josh", "indian", 150, 13, [["1 bowl", 300]], "rogan josh lamb curry"],
  ["tandoori", "Tandoori chicken", "indian", 160, 25, [["1 leg piece", 120], ["1 palm (100 g)", 100]], "tandoori chicken"],
  ["chana-masala", "Chana masala", "indian", 130, 6, [["1 bowl", 250]], "chana masala chole chickpea curry"],
  ["dal", "Dal (lentil curry)", "indian", 110, 6, [["1 bowl", 250], ["1 cupped hand", 120]], "dal daal dhal tadka lentil"],
  ["rajma", "Rajma (kidney bean curry)", "indian", 120, 6, [["1 bowl", 250]], "rajma"],
  ["palak-paneer", "Palak paneer", "indian", 150, 7, [["1 bowl", 250]], "palak paneer saag"],
  ["paneer-tikka", "Paneer tikka", "indian", 260, 15, [["1 serving", 150]], "paneer tikka"],
  ["aloo-gobi", "Aloo gobi", "indian", 90, 2.5, [["1 bowl", 200]], "aloo gobi potato cauliflower"],
  ["biryani", "Chicken biryani", "indian", 170, 8, [["1 plate", 350], ["1 fist (1 cup)", 180]], "biryani chicken mutton"],
  ["basmati", "Basmati rice, cooked", "indian", 121, 3.5, [["1 fist (1 cup)", 160]], "basmati rice"],
  ["jeera-rice", "Jeera rice / pulao", "indian", 150, 3, [["1 fist (1 cup)", 160]], "jeera rice pulao"],
  ["naan", "Naan", "indian", 290, 9, [["1 naan", 90], ["1/2 naan", 45]], "naan bread"],
  ["garlic-naan", "Garlic naan", "indian", 300, 9, [["1 naan", 95]], "garlic naan"],
  ["roti", "Roti / chapati", "indian", 297, 8, [["1 roti", 40]], "roti chapati phulka"],
  ["paratha", "Paratha", "indian", 320, 7, [["1 paratha", 80]], "paratha aloo paratha"],
  ["puri", "Puri", "indian", 380, 7, [["1 puri", 25]], "puri poori"],
  ["dosa", "Dosa, plain", "indian", 168, 4, [["1 dosa", 100]], "dosa"],
  ["masala-dosa", "Masala dosa", "indian", 180, 4, [["1 dosa", 200]], "masala dosa"],
  ["idli", "Idli", "indian", 130, 4, [["1 idli", 40], ["3 idli", 120]], "idli"],
  ["sambar", "Sambar", "indian", 70, 3, [["1 bowl", 200]], "sambar"],
  ["upma", "Upma", "indian", 150, 3.5, [["1 bowl", 200]], "upma"],
  ["poha", "Poha", "indian", 130, 2.5, [["1 plate", 200]], "poha"],
  ["samosa", "Samosa (vegetable)", "indian", 260, 4.5, [["1 samosa", 100]], "samosa"],
  ["pakora", "Pakora / bhaji", "indian", 300, 7, [["1 piece", 25], ["5 pieces", 125]], "pakora bhaji onion bhaji"],
  ["vada-pav", "Vada pav", "indian", 210, 5, [["1 vada pav", 140]], "vada pav"],
  ["raita", "Raita", "indian", 60, 3, [["1 small bowl", 100]], "raita"],
  ["gulab-jamun", "Gulab jamun", "indian", 320, 5, [["1 piece", 40]], "gulab jamun"],
  ["kheer", "Kheer (rice pudding)", "indian", 140, 4, [["1 bowl", 150]], "kheer payasam rice pudding"],
  ["lassi", "Lassi, sweet", "indian", 90, 3, [["1 glass", 250]], "lassi mango lassi"],
  ["chai", "Masala chai (with milk and sugar)", "indian", 50, 2, [["1 cup", 200]], "chai tea masala"],
  // ---- Chinese ----
  ["sweet-sour", "Sweet and sour chicken", "chinese", 230, 11, [["1 serving", 300], ["1 cupped hand", 120]], "sweet and sour chicken pork"],
  ["kung-pao", "Kung pao chicken", "chinese", 160, 14, [["1 serving", 300]], "kung pao gong bao chicken"],
  ["general-tso", "General Tso's / orange chicken", "chinese", 250, 13, [["1 serving", 300]], "general tso orange chicken sesame"],
  ["beef-broccoli", "Beef and broccoli", "chinese", 120, 10, [["1 serving", 300]], "beef broccoli"],
  ["mapo-tofu", "Mapo tofu", "chinese", 120, 7, [["1 bowl", 250]], "mapo tofu"],
  ["char-siu", "Char siu (BBQ pork)", "chinese", 270, 22, [["1 palm (100 g)", 100]], "char siu bbq pork"],
  ["roast-duck", "Roast duck (with skin)", "chinese", 300, 19, [["1 serving", 150]], "roast duck peking duck"],
  ["dumplings", "Dumplings, steamed (pork)", "chinese", 200, 8, [["1 dumpling", 25], ["6 dumplings", 150]], "dumplings jiaozi"],
  ["potstickers", "Potstickers / fried dumplings", "chinese", 230, 8, [["1 piece", 30], ["6 pieces", 180]], "potstickers guotie fried dumplings"],
  ["siu-mai", "Siu mai", "chinese", 200, 10, [["1 piece", 20], ["4 pieces", 80]], "siu mai shumai dim sum"],
  ["har-gow", "Har gow (shrimp dumpling)", "chinese", 160, 7, [["1 piece", 20], ["4 pieces", 80]], "har gow dim sum"],
  ["bao", "Steamed bun (pork bao)", "chinese", 240, 9, [["1 bun", 80]], "bao baozi char siu bao"],
  ["spring-roll", "Spring roll, fried", "chinese", 250, 5, [["1 roll", 60]], "spring roll egg roll"],
  ["wonton-soup", "Wonton soup", "chinese", 50, 3.5, [["1 bowl", 400]], "wonton soup"],
  ["hot-sour", "Hot and sour soup", "chinese", 40, 2.5, [["1 bowl", 350]], "hot and sour soup"],
  ["congee", "Congee (chicken)", "chinese", 60, 3, [["1 bowl", 350]], "congee jook rice porridge"],
  ["chow-fun", "Beef chow fun", "chinese", 180, 6, [["1 plate", 400]], "chow fun ho fun"],
  // ---- Japanese & Korean ----
  ["nigiri", "Sushi nigiri", "japkor", 150, 7, [["1 piece", 40], ["6 pieces", 240]], "nigiri sushi salmon tuna"],
  ["sashimi", "Sashimi (salmon or tuna)", "japkor", 180, 21, [["5 slices", 100]], "sashimi"],
  ["ramen", "Ramen (pork broth)", "japkor", 110, 4.5, [["1 bowl", 650]], "ramen tonkotsu shoyu miso noodles"],
  ["udon", "Udon noodle soup", "japkor", 70, 2.5, [["1 bowl", 500]], "udon"],
  ["miso-soup", "Miso soup", "japkor", 30, 2, [["1 bowl", 240]], "miso soup"],
  ["teriyaki", "Chicken teriyaki", "japkor", 180, 20, [["1 serving", 150]], "teriyaki chicken"],
  ["katsu", "Chicken katsu / tonkatsu", "japkor", 270, 18, [["1 cutlet", 150]], "katsu tonkatsu cutlet"],
  ["katsu-curry", "Katsu curry with rice", "japkor", 170, 7, [["1 plate", 450]], "katsu curry japanese curry"],
  ["gyoza", "Gyoza", "japkor", 200, 8, [["1 piece", 25], ["6 pieces", 150]], "gyoza"],
  ["tempura", "Tempura (shrimp or vegetable)", "japkor", 250, 10, [["1 piece", 25], ["5 pieces", 125]], "tempura"],
  ["edamame", "Edamame", "japkor", 121, 12, [["1 cup", 155], ["1 cupped hand", 75]], "edamame soy beans"],
  ["onigiri", "Onigiri (rice ball)", "japkor", 170, 3.5, [["1 onigiri", 110]], "onigiri rice ball"],
  ["bento", "Chicken teriyaki bento (with rice)", "japkor", 160, 8, [["1 box", 400]], "bento box"],
  ["kimchi", "Kimchi", "japkor", 15, 1.1, [["1 side portion", 50]], "kimchi"],
  ["bibimbap", "Bibimbap", "japkor", 120, 6, [["1 bowl", 500]], "bibimbap"],
  ["bulgogi", "Bulgogi", "japkor", 190, 17, [["1 serving", 200]], "bulgogi korean bbq beef"],
  ["kfc-korean", "Korean fried chicken", "japkor", 290, 18, [["1 piece", 60], ["6 pieces", 360]], "korean fried chicken yangnyeom"],
  ["pork-belly", "Grilled pork belly (samgyeopsal)", "japkor", 460, 14, [["1 palm (100 g)", 100]], "samgyeopsal pork belly korean bbq"],
  ["japchae", "Japchae", "japkor", 150, 3, [["1 plate", 250]], "japchae glass noodles"],
  ["kimbap", "Kimbap", "japkor", 140, 5, [["1 roll", 230], ["4 slices", 80]], "kimbap gimbap"],
  ["tteokbokki", "Tteokbokki", "japkor", 160, 3, [["1 plate", 300]], "tteokbokki rice cakes"],
  // ---- Southeast Asian ----
  ["pad-thai", "Pad thai", "seasia", 170, 7, [["1 plate", 350]], "pad thai noodles"],
  ["green-curry", "Thai green or red curry (chicken)", "seasia", 140, 9, [["1 bowl", 300]], "green curry red curry thai"],
  ["massaman", "Massaman curry", "seasia", 160, 9, [["1 bowl", 300]], "massaman curry"],
  ["tom-yum", "Tom yum soup", "seasia", 40, 4, [["1 bowl", 350]], "tom yum tom kha soup"],
  ["som-tam", "Green papaya salad (som tam)", "seasia", 50, 2, [["1 plate", 200]], "som tam papaya salad"],
  ["mango-sticky", "Mango sticky rice", "seasia", 200, 3, [["1 serving", 200]], "mango sticky rice"],
  ["pho", "Pho (beef noodle soup)", "seasia", 55, 4, [["1 bowl", 800]], "pho beef noodle soup vietnamese"],
  ["banh-mi", "Banh mi", "seasia", 230, 10, [["1 sandwich", 250]], "banh mi vietnamese sandwich"],
  ["fresh-roll", "Fresh spring roll (rice paper)", "seasia", 110, 5, [["1 roll", 80]], "fresh spring roll summer roll goi cuon"],
  ["nasi-goreng", "Nasi goreng", "seasia", 170, 6, [["1 plate", 350]], "nasi goreng fried rice indonesian"],
  ["nasi-lemak", "Nasi lemak", "seasia", 180, 5, [["1 plate", 400]], "nasi lemak malaysian"],
  ["mee-goreng", "Mee goreng", "seasia", 170, 6, [["1 plate", 350]], "mee goreng mie goreng fried noodles"],
  ["laksa", "Laksa", "seasia", 110, 5, [["1 bowl", 600]], "laksa curry noodle soup"],
  ["satay", "Chicken satay with peanut sauce", "seasia", 220, 18, [["1 skewer", 30], ["5 skewers", 150]], "satay sate"],
  ["rendang", "Beef rendang", "seasia", 190, 16, [["1 serving", 200]], "rendang"],
  ["chicken-rice", "Hainanese chicken rice", "seasia", 175, 9, [["1 plate", 400]], "hainanese chicken rice"],
  ["adobo", "Chicken adobo", "seasia", 190, 18, [["1 serving", 200]], "adobo filipino"],
  ["pancit", "Pancit", "seasia", 140, 6, [["1 plate", 300]], "pancit canton bihon"],
  ["sinigang", "Sinigang", "seasia", 40, 4, [["1 bowl", 400]], "sinigang sour soup"],
  ["lumpia", "Lumpia, fried", "seasia", 250, 8, [["1 piece", 40]], "lumpia shanghai"],
  ["lechon", "Lechon / roast pork with skin", "seasia", 350, 20, [["1 palm (100 g)", 100]], "lechon roast pork crackling"],
  // ---- Middle Eastern & Mediterranean ----
  ["falafel", "Falafel", "mideast", 333, 13, [["1 piece", 17], ["5 pieces", 85]], "falafel"],
  ["shawarma", "Chicken shawarma wrap", "mideast", 230, 13, [["1 wrap", 300]], "shawarma wrap"],
  ["doner", "Doner kebab in pitta", "mideast", 250, 12, [["1 kebab", 350]], "doner kebab donair"],
  ["shish", "Chicken shish kebab", "mideast", 165, 27, [["1 skewer", 100]], "shish kebab shish taouk"],
  ["kofta", "Kofta kebab", "mideast", 250, 18, [["1 skewer", 80]], "kofta kofte"],
  ["kabsa", "Chicken kabsa / mandi", "mideast", 170, 10, [["1 plate", 400]], "kabsa mandi machboos"],
  ["mujaddara", "Mujaddara (lentils and rice)", "mideast", 160, 6, [["1 plate", 300]], "mujaddara mujadara"],
  ["tabbouleh", "Tabbouleh", "mideast", 120, 2, [["1 cup", 160]], "tabbouleh tabouli"],
  ["fattoush", "Fattoush", "mideast", 90, 2, [["1 bowl", 150]], "fattoush salad"],
  ["baba-ganoush", "Baba ganoush", "mideast", 110, 2, [["2 tbsp", 30]], "baba ganoush moutabal"],
  ["pita", "Pita bread", "mideast", 275, 9, [["1 pita", 60]], "pita pitta bread"],
  ["labneh", "Labneh", "mideast", 140, 8, [["2 tbsp", 30]], "labneh"],
  ["manakish", "Manakish (zaatar)", "mideast", 320, 8, [["1 manakish", 120]], "manakish manaeesh zaatar"],
  ["shakshuka", "Shakshuka", "mideast", 110, 6.5, [["1 serving", 250]], "shakshuka eggs tomato"],
  ["ful", "Ful medames", "mideast", 110, 7, [["1 bowl", 250]], "ful medames foul fava beans"],
  ["koshari", "Koshari", "mideast", 150, 5, [["1 bowl", 350]], "koshari kushari"],
  ["lentil-soup", "Lentil soup", "mideast", 60, 4, [["1 bowl", 300]], "lentil soup shorbat adas mercimek"],
  ["greek-salad", "Greek salad (with feta)", "mideast", 110, 3.5, [["1 bowl", 250]], "greek salad horiatiki"],
  ["feta", "Feta cheese", "mideast", 264, 14, [["1 oz", 28], ["1 cupped hand", 50]], "feta"],
  ["moussaka", "Moussaka", "mideast", 140, 7, [["1 serving", 300]], "moussaka"],
  ["souvlaki", "Souvlaki (pork or chicken)", "mideast", 200, 25, [["1 skewer", 100]], "souvlaki"],
  ["gyro", "Gyro wrap", "mideast", 230, 11, [["1 gyro", 300]], "gyro gyros"],
  ["spanakopita", "Spanakopita", "mideast", 300, 8, [["1 piece", 100]], "spanakopita spinach pie"],
  ["dolma", "Dolma (stuffed vine leaves)", "mideast", 150, 3, [["1 piece", 30], ["5 pieces", 150]], "dolma dolmades warak enab"],
  ["baklava", "Baklava", "mideast", 430, 6, [["1 piece", 40]], "baklava"],
  // ---- Mexican & Latin American ----
  ["taco-beef", "Taco (beef, corn tortilla)", "latin", 210, 10, [["1 taco", 90], ["3 tacos", 270]], "taco tacos beef al pastor"],
  ["taco-chicken", "Taco (chicken)", "latin", 190, 12, [["1 taco", 90], ["3 tacos", 270]], "chicken taco"],
  ["taco-fish", "Fish taco", "latin", 200, 10, [["1 taco", 110]], "fish taco baja"],
  ["corn-tortilla", "Corn tortilla", "latin", 218, 5.7, [["1 tortilla", 26]], "corn tortilla"],
  ["quesadilla", "Quesadilla (cheese)", "latin", 300, 13, [["1 quesadilla", 180]], "quesadilla"],
  ["enchilada", "Enchilada (chicken)", "latin", 170, 10, [["1 enchilada", 130]], "enchiladas"],
  ["nachos", "Nachos with cheese", "latin", 320, 8, [["1 plate", 250]], "nachos"],
  ["guacamole", "Guacamole", "latin", 155, 2, [["2 tbsp", 30], ["1/2 cup", 120]], "guacamole guac"],
  ["salsa", "Salsa", "latin", 30, 1.5, [["2 tbsp", 30]], "salsa pico de gallo"],
  ["refried", "Refried beans", "latin", 90, 5.5, [["1/2 cup", 120]], "refried beans frijoles"],
  ["mexican-rice", "Mexican / Spanish rice", "latin", 140, 3, [["1 fist (1 cup)", 160]], "mexican rice arroz rojo"],
  ["tamal", "Tamale", "latin", 210, 7, [["1 tamale", 140]], "tamale tamal"],
  ["pozole", "Pozole", "latin", 70, 5, [["1 bowl", 400]], "pozole posole"],
  ["fajitas", "Chicken fajitas (filling)", "latin", 120, 14, [["1 serving", 250]], "fajitas"],
  ["chilaquiles", "Chilaquiles", "latin", 200, 7, [["1 plate", 300]], "chilaquiles"],
  ["elote", "Elote (street corn)", "latin", 150, 4, [["1 ear", 150]], "elote street corn"],
  ["churros", "Churros", "latin", 420, 5, [["1 churro", 40]], "churros"],
  ["empanada", "Empanada (beef)", "latin", 300, 10, [["1 empanada", 100]], "empanada pastelito"],
  ["arepa", "Arepa, plain", "latin", 220, 4.5, [["1 arepa", 100]], "arepa"],
  ["arepa-filled", "Arepa with cheese or meat", "latin", 260, 10, [["1 arepa", 150]], "arepa reina pepiada"],
  ["pupusa", "Pupusa", "latin", 230, 8, [["1 pupusa", 120]], "pupusa"],
  ["gallo-pinto", "Gallo pinto (rice and beans)", "latin", 140, 5, [["1 fist (1 cup)", 175]], "gallo pinto moros cristianos"],
  ["arroz-pollo", "Arroz con pollo", "latin", 150, 9, [["1 plate", 400]], "arroz con pollo"],
  ["feijoada", "Feijoada", "latin", 150, 10, [["1 bowl", 300]], "feijoada"],
  ["picanha", "Picanha / grilled beef (churrasco)", "latin", 260, 22, [["1 palm (100 g)", 100]], "picanha churrasco steak"],
  ["pao-queijo", "Pão de queijo (cheese bread)", "latin", 330, 6, [["1 piece", 25]], "pao de queijo cheese bread"],
  ["ceviche", "Ceviche", "latin", 90, 14, [["1 cup", 200]], "ceviche"],
  ["lomo-saltado", "Lomo saltado", "latin", 150, 11, [["1 plate", 350]], "lomo saltado peru"],
  ["ropa-vieja", "Ropa vieja", "latin", 160, 16, [["1 serving", 200]], "ropa vieja"],
  ["picadillo", "Picadillo", "latin", 180, 14, [["1 serving", 200]], "picadillo"],
  ["cuban-sandwich", "Cuban sandwich", "latin", 260, 15, [["1 sandwich", 300]], "cuban sandwich cubano"],
  ["tostones", "Tostones (fried green plantain)", "latin", 230, 1.2, [["5 pieces", 80]], "tostones patacones"],
  ["mofongo", "Mofongo", "latin", 200, 3, [["1 serving", 250]], "mofongo"],
  ["tres-leches", "Tres leches cake", "latin", 280, 6, [["1 slice", 120]], "tres leches"],
  ["horchata", "Horchata", "latin", 70, 0.5, [["1 glass", 250]], "horchata"],
  // ---- European ----
  ["bolognese", "Spaghetti bolognese", "european", 130, 7, [["1 plate", 400], ["1 fist (1 cup)", 220]], "spaghetti bolognese pasta"],
  ["lasagne", "Lasagne", "european", 140, 8, [["1 slice", 300]], "lasagna lasagne"],
  ["carbonara", "Pasta carbonara", "european", 190, 8, [["1 plate", 350]], "carbonara"],
  ["risotto", "Risotto (mushroom)", "european", 140, 4, [["1 plate", 350]], "risotto"],
  ["paella", "Paella (seafood)", "european", 150, 8, [["1 plate", 400]], "paella"],
  ["tortilla-espanola", "Spanish omelette (tortilla española)", "european", 170, 6, [["1 slice", 150]], "tortilla espanola spanish omelette"],
  ["gazpacho", "Gazpacho", "european", 40, 1, [["1 bowl", 250]], "gazpacho"],
  ["fish-chips", "Fish and chips", "european", 200, 10, [["1 plate", 450]], "fish and chips"],
  ["full-english", "Full English breakfast", "european", 180, 9, [["1 plate", 450]], "full english fry up breakfast"],
  ["shepherds-pie", "Shepherd's / cottage pie", "european", 120, 7, [["1 serving", 350]], "shepherds pie cottage pie"],
  ["roast-beef", "Roast beef (lean)", "european", 200, 29, [["1 palm (100 g)", 100], ["3 slices", 90]], "roast beef sunday roast"],
  ["roast-potatoes", "Roast potatoes", "european", 150, 2.5, [["3 pieces", 150]], "roast potatoes"],
  ["yorkshire", "Yorkshire pudding", "european", 250, 8, [["1 pudding", 40]], "yorkshire pudding"],
  ["croissant", "Croissant", "european", 406, 8, [["1 croissant", 60]], "croissant"],
  ["pain-choc", "Pain au chocolat", "european", 420, 7, [["1 pastry", 70]], "pain au chocolat chocolate croissant"],
  ["quiche", "Quiche lorraine", "european", 280, 10, [["1 slice", 150]], "quiche"],
  ["ratatouille", "Ratatouille", "european", 60, 1.5, [["1 bowl", 250]], "ratatouille"],
  ["crepe", "Crêpe (sweet)", "european", 230, 6, [["1 crêpe", 80]], "crepe pancake"],
  ["waffle", "Waffle", "european", 290, 8, [["1 waffle", 75]], "waffle"],
  ["schnitzel", "Schnitzel (breaded)", "european", 260, 19, [["1 schnitzel", 150]], "schnitzel wiener"],
  ["bratwurst", "Bratwurst", "european", 300, 13, [["1 sausage", 85]], "bratwurst"],
  ["pretzel", "Soft pretzel", "european", 340, 8, [["1 pretzel", 115]], "pretzel brezel"],
  ["goulash", "Goulash", "european", 100, 8, [["1 bowl", 350]], "goulash gulyas"],
  ["pierogi", "Pierogi", "european", 190, 6, [["1 piece", 35], ["6 pieces", 210]], "pierogi perogies"],
  ["borscht", "Borscht", "european", 40, 1.5, [["1 bowl", 350]], "borscht"],
  ["tiramisu", "Tiramisu", "european", 280, 5, [["1 portion", 100]], "tiramisu"],
  ["gelato", "Gelato", "european", 210, 4, [["1 scoop", 70]], "gelato"],
  // ---- American ----
  ["ribs", "BBQ pork ribs", "american", 280, 21, [["1 rib", 50], ["half rack", 300]], "ribs bbq"],
  ["pulled-pork", "Pulled pork sandwich", "american", 230, 13, [["1 sandwich", 250]], "pulled pork"],
  ["cheesesteak", "Philly cheesesteak", "american", 230, 13, [["1 sandwich", 350]], "cheesesteak philly"],
  ["grilled-cheese", "Grilled cheese sandwich", "american", 330, 12, [["1 sandwich", 120]], "grilled cheese toastie"],
  ["blt", "BLT sandwich", "american", 260, 10, [["1 sandwich", 150]], "blt"],
  ["club", "Club sandwich", "american", 230, 13, [["1 sandwich", 250]], "club sandwich"],
  ["pbj", "Peanut butter and jelly sandwich", "american", 350, 11, [["1 sandwich", 100]], "pb&j pbj"],
  ["bagel-cc", "Bagel with cream cheese", "american", 290, 9, [["1 bagel", 130]], "bagel cream cheese"],
  ["caesar", "Caesar salad", "american", 160, 5, [["1 bowl", 250]], "caesar salad"],
  ["cobb", "Cobb salad", "american", 140, 10, [["1 bowl", 350]], "cobb salad"],
  ["chili", "Chili con carne", "american", 110, 9, [["1 bowl", 300]], "chili con carne"],
  ["meatloaf", "Meatloaf", "american", 200, 14, [["1 slice", 150]], "meatloaf"],
  ["clam-chowder", "Clam chowder", "american", 90, 4, [["1 bowl", 250]], "clam chowder"],
  ["biscuits-gravy", "Biscuits and gravy", "american", 200, 5, [["1 plate", 300]], "biscuits gravy"],
  ["cornbread", "Cornbread", "american", 330, 7, [["1 piece", 60]], "cornbread"],
  ["apple-pie", "Apple pie", "american", 270, 2.5, [["1 slice", 125]], "apple pie"],
  ["cheesecake", "Cheesecake", "american", 320, 6, [["1 slice", 120]], "cheesecake"],
  ["brownie", "Brownie", "american", 450, 5, [["1 brownie", 55]], "brownie"],
  ["milkshake", "Milkshake", "american", 110, 3.5, [["1 regular", 350]], "milkshake shake"],
  ["energy-drink", "Energy drink", "american", 45, 0, [["1 can (250 ml)", 250], ["1 large can (473 ml)", 473]], "energy drink red bull monster"],
  // ---- more Caribbean ----
  ["dhalpuri", "Roti (dhalpuri) with curry", "carib", 220, 9, [["1 roti wrap", 350]], "roti dhalpuri trinidad curry"],
  ["doubles", "Doubles", "carib", 230, 7, [["1 doubles", 120]], "doubles trinidad"],
  ["pelau", "Pelau", "carib", 160, 8, [["1 plate", 350]], "pelau"],
  ["stew-peas", "Stew peas", "carib", 140, 8, [["1 bowl", 300]], "stew peas"],
  ["escovitch", "Escovitch fish", "carib", 200, 18, [["1 piece", 150]], "escovitch fish"],
  ["saltfish-fritter", "Saltfish fritters", "carib", 260, 9, [["1 fritter", 40]], "saltfish fritters stamp and go"],
  ["bun-cheese", "Bun and cheese", "carib", 340, 8, [["1 slice", 100]], "bun and cheese easter bun"],
  ["coucou", "Cou-cou and flying fish", "carib", 150, 9, [["1 plate", 350]], "coucou flying fish barbados"]
];
